export const portfolioProjects = [
  {
    name: "Gray Matters Technology Services",
    url: "https://www.graymatterstech.com",
    image: "/portfolio/gray-matters-tech.png",
    category: "Technology services",
    summary: "A federal IT and AI modernization site built around credibility, mission clarity, and secure service positioning.",
  },
  {
    name: "Peppers and Vibes",
    url: "https://www.peppersandvibes.com",
    image: "/portfolio/peppers-and-vibes.png",
    category: "Restaurant / food brand",
    summary: "A warm, flavorful food brand presence designed to make the business feel immediate, local, and memorable.",
  },
  {
    name: "Design Haven Build",
    url: "https://www.designhavenbuild.com",
    image: "/portfolio/design-haven-build.png",
    category: "Construction / design-build",
    summary: "A service business website shaped around trust, project confidence, and clean conversion paths.",
  },
  {
    name: "Bougie and Company",
    url: "https://www.bougieandcompany.com",
    image: "/portfolio/bougie-and-company.png",
    category: "Beauty / lifestyle",
    summary: "A boutique brand experience with polished visuals, clear service framing, and a premium small-business feel.",
  },
  {
    name: "Annas Air",
    url: "https://www.annasair.com",
    image: "/portfolio/annas-air.png",
    category: "HVAC / home services",
    summary: "A local service site focused on fast trust-building, service clarity, and customer contact momentum.",
  },
  {
    name: "AS Detailing",
    url: "https://www.asdetailing.org",
    image: "/portfolio/as-detailing.png",
    category: "Auto detailing",
    summary: "A visual service site built to show care, quality, and simple next steps for booking detailing work.",
  },
  {
    name: "Ghost GEO",
    url: "https://geo.ghostai.solutions",
    image: "/portfolio/ghost-geo.png",
    category: "AI visibility platform",
    summary: "A GhostAI product surface for SEO, AEO, and generative engine visibility workflows.",
  },
  {
    name: "Blue Anchor Seafood",
    url: "https://www.blueanchorseafood.com",
    image: "/portfolio/blue-anchor-seafood.png",
    category: "Restaurant / seafood",
    summary: "A restaurant website concept with strong food imagery, direct menu access, and reservation momentum.",
  },
];
